### ISSUE TITLE
Problem with multi-monitor setups

### ISSUE THREAD

**Issue by iesmith2** [skiselkov/BetterPushbackC#118] opened 2017-08-22 20:45 UTC
Hi,

Firstly, congrats on what you've achieved so far... Excellent plugin.

I've come across an issue with multi monitors - on the pre-plan pushback page, I've found that in order to bring the aircraft outline icon to the correct position to place a segment, I have to move the mouse far enough that it travels onto another monitor. This is due to the icon not being 'synced' to the mouse pointer. This means that I can't then click to place the segment as the main screen has lost mouse focus.

Hope I've explained that sufficiently well... I can't seem to get a screenshot.

thanks,
Iain

**Comment by skiselkov** [comment] 2017-08-22 23:37
This is a duplicate of #26. As I've explained in that bug, X-Plane's current plugin SDK unfortunately does not expose any method of detecting or working with multiple monitors, so BetterPushback unfortunately isn't able to properly compute mouse locations with respect to real-world coordinates. I have been promised updates to the SDK in XP 11.10, so hopefully by then I will be able to finally implement this properly.

**Closed by skiselkov** 2017-08-22 23:37 UTC
Labels: bug, duplicate
