### ISSUE TITLE
Crash when X-Plane 10 closes

### ISSUE THREAD

**Issue by McDonne11** [skiselkov/BetterPushbackC#14] opened 2017-07-17 06:28 UTC
Hello!
When I trying to close X-Plane, appears the error:
"Microsoft Visual C ++ Runtime Library This application has been requested the Runtime to terminate it in an unusual way. Please, contact the application support team for more information". And crashing X-Plane.
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1151723/Log.txt)
Thanx in advance!

**Comment by McDonne11** [comment] 2017-07-17 08:17
Also, after performing pushback (MD-80 by RotateSim), after disconecting tug X-Plane has crashed with error StackHash_6131.
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1151922/Log.txt)

**Comment by skiselkov** [comment] 2017-07-17 12:08
Thank you for the report, I believe I understand what the problem is. Fix is in the works.

**Comment by skiselkov** [comment] 2017-07-17 12:24
Please test with release v0.13.

**Comment by McDonne11** [comment] 2017-07-17 13:07
Many Thanx!
I'll test it right now.

**Comment by McDonne11** [comment] 2017-07-17 15:26
Thank you so much! Both problems are gone.

**Comment by skiselkov** [comment] 2017-07-17 16:08
Thanks for reporting & testing.

**Closed by skiselkov** 2017-07-17 16:08 UTC
Labels: bug, testing
