### ISSUE TITLE
Not compatible with Zibomod 737?

### ISSUE THREAD

**Issue by DemonTraitor** [skiselkov/BetterPushbackC#112] opened 2017-08-18 19:07 UTC
(https://drive.google.com/drive/folders/0B-tdl3VvPeOOYm12Wm80V04wdDQ)

I seem to be able to plan a pushback, but when I start a PB, it says "ready to connect" and then a runtime error occurs and XP11,05 crashes to desktop.

When are you going to start charging for this plugin? it is awesome and I am sure many will be happy to pay for your efforts!!!

Demon^^

EDIT: Windows 10 etc...

**Comment by skiselkov** [comment] 2017-08-18 19:09
Please attach your Log.txt, it should contain vital info I need to debug this.

> When are you going to start charging for this plugin?

Never, but I do plan on setting up a donation page, so if anybody really, really **wants** to throw a few bucks my way, they can.

**Comment by DemonTraitor** [comment] 2017-08-18 19:11
I shall run it again now and send my log...

**Comment by DemonTraitor** [comment] 2017-08-18 19:15
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1235415/Log.txt)

here you go :)

**Comment by skiselkov** [comment] 2017-08-18 19:23
Alright, I know what's happening. Zibo came out with another update, didn't he?

**Comment by DemonTraitor** [comment] 2017-08-18 19:25
Yes indeed he did

-Android

**Comment by beattleboy** [comment] 2017-08-18 20:53
The problem is, people are reporting issues they are having with this plugin on his site, and he is making corrections for it, countering what fixes you are making, when people are reporting them here.  It is a back and forth thing as you both update pretty much on a daily basis.  :)

**Comment by beattleboy** [comment] 2017-08-19 00:28
He just updated it again, and his notes mentions better compatibility with your plug in... what ever that means.

**Comment by rnorris03** [comment] 2017-08-21 14:53
Yes, I always use the zibo 737. It crashes x-plane right before it starts to push. I'm using ubuntu 16.04.

**Comment by skiselkov** [comment] 2017-08-23 13:31
Fixed in v0.44. Please test.

**Comment by rnorris03** [comment] 2017-08-23 16:28
Ok, I will check it out now!

**Comment by rnorris03** [comment] 2017-08-23 16:41
Works perfectly with the Zibo mod 737-800. Just tested it. No crashes.

**Comment by skiselkov** [comment] 2017-08-23 17:22
@rnorris03 Thanks for testing. Closing as fixed.

**Closed by skiselkov** 2017-08-23 17:22 UTC
Labels: bug, testing

**Comment by DemonTraitor** [comment] 2017-08-23 20:55
Perfect. Thank you 😁😁😁

-Android
