### ISSUE TITLE
Microsoft Visual C++ Runtime Library

### ISSUE THREAD

**Issue by notam9** [skiselkov/BetterPushbackC#111] opened 2017-08-18 17:02 UTC
Error right before the tractor connect to the main gear: "This application has requested the runtime to terminate it in an unusual way"

**Comment by skiselkov** [comment] 2017-08-18 19:18
Can you please attach your `Log.txt`.

**Comment by Nus71** [comment] 2017-08-22 18:25
Hi, just the same thing happened to me. Just before connecting the pusch the same error has come out. 
Thank you for taking time in it.
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1242968/Log.txt)

**Comment by skiselkov** [comment] 2017-08-22 19:32
@Nus71 This is caused by a change in Zibo's 737. The latest one should contain a fix. I'll be pushing a fix to BP soon as well, which takes care of this from BP's end.

**Comment by Nus71** [comment] 2017-08-22 19:47
as always thank you very much! Skiselkov

**Comment by skiselkov** [comment] 2017-08-23 13:32
Fixed in v0.44, please test.

**Comment by skiselkov** [comment] 2017-08-23 17:23
Closing as dup of #111, which was fixed.

**Closed by skiselkov** 2017-08-23 17:23 UTC
Labels: bug
