### ISSUE TITLE
Better Pushback not working with latest zibo mod and latest version of pushback

### ISSUE THREAD

**Issue by thedaedalus** [skiselkov/BetterPushbackC#96] opened 2017-08-11 08:55 UTC
With the latest version of the Zibo mod 3.06d the push back truck wont move. It appears it does not see the parking break coming off.

What I have observed is as soon as the pushback truck engages the parking break light inside the aircraft goes out and will never come back on no matter what state the parking brake lever is at. Manually trying to change the data refs have no effect.

**Comment by beattleboy** [comment] 2017-08-12 00:25
This may not be a BP issue.  As Zibo has now implemented automatic chalks on load up, with no way of saving it to be off on load up, with 3.06d, if you don't turn them off, the tug won't move the aircraft (because of the chalks).  With 06d, and the option to turn off chalks with parking brake application, now, you have to hit the parking brake off, then on again before actual push back.   Once figured out, BP works as normal.  This is more a Zibo mod issue then a BP one, although, if you forget to remove the chalks, do the brake off, on, off, it causes bugs in the tow, causing it to do donuts with the aircraft over and over.

**Comment by skiselkov** [comment] 2017-08-12 02:24
I'm kinda tired of zibo breaking compatibility every week or so, but I'll check what the situation is.
@beattleboy If it is going in donuts, I really do need to check if Zibo isn't preventing nosewheel steering from being enabled (because without it the nosewheel steering functionality in X-Plane is all broken). I might implement a check before connection to make sure BP can either turn your NWS on, or if it can't, it will simply refuse to connect (throwing off the side of the airport is definitely not what it should be doing).

**Comment by beattleboy** [comment] 2017-08-12 09:48
What is happening, at least for me for the donuts is when this happens.  I am ready to be pushed.  I forget to turn off the chalks.  I release parking brake...  Nothing happens, as the plane is chalked.  I go oops.  Turn on parking break, and now in 3.06d, turn off parking brake again to remove chalks.  Since there was a delay in this, It looks like the tug is trying to make up time and goes into double speed, then starts going in circles at the first turn.  If I remember to remove the chalks before I start the tow, it works as normal and everything is fine.  I think the nosewheel steering is the same, its the chalks that mess things up.

**Comment by beattleboy** [comment] 2017-08-12 11:12
This is what it does if chalks not removed first.

https://youtu.be/pwi6hkd-icI

**Comment by skiselkov** [comment] 2017-08-12 11:44
@beattleboy Hehe, what a funny bug. I'll try the plane myself, should be relatively straightforward figuring out what's wrong.

**Comment by skiselkov** [comment] 2017-08-12 12:12
I see what the problem is. Fix will be included in next build tonight.

**Comment by skiselkov** [comment] 2017-08-15 01:27
Implemented automatic zibo 737 chock removal and also resolved the potential for the bug resurface if we can't push again.

**Comment by JoseBDA** [comment] 2017-08-15 09:11
I think we have a return of an old issue where the parking brake can't be activated after pushback, with zibo 737. This has happened before and zibo cured it.

**Comment by rcburse** [comment] 2017-08-17 04:18
So if you have the chocks option on, the fix works. But I had the option turned off and when I released the park brake the donuts started. Thats fine I will just leave the chocks option to on. GREAT PUSHBACK plugin you provided us. Thank you.

**Comment by skiselkov** [comment] 2017-08-17 23:32
I'll close this for now. I can't reproduce the donuts, works ok for me (chocks or no chocks). If somebody else reports this I'll give this another go at reproduction.

**Closed by skiselkov** 2017-08-17 23:32 UTC
Labels: bug, testing

**Comment by Gegels** [comment] 2024-12-28 13:29
it seems to happen again with the Better Pushback 1.8.2 and the Zibo V  XP12_4_03_8.
