### ISSUE TITLE
nose wheel steer

### ISSUE THREAD

**Issue by cpuwolf** [skiselkov/BetterPushbackC#19] opened 2017-07-17 22:28 UTC
I have nose wheel steer setting on XP11, then by default BetterPushbackC cannot turn. and I found the problem is about dataref

sim/cockpit2/controls/nosewheel_steer_on

**Comment by skiselkov** [comment] 2017-07-17 22:39
I'm not sure I understand what the issue is. Yes, if you disable nosewheel steering, then BP won't work (because it works by steering the nosewheel). But why are you doing that? You shouldn't be changing datarefs unless you know what you are doing. To have BP work, simply leave `sim/cockpit2/controls/nosewheel_steer_on` set to `1` and everything will work as it should.

**Comment by cpuwolf** [comment] 2017-07-18 03:41
the problem is my zibo 738 on XP11 cannot turn left/right while pushback

**Comment by cpuwolf** [comment] 2017-07-18 03:47
if you have your joystick setting about steering wheel, then you will find this plugin wont work any more

**Comment by skiselkov** [comment] 2017-07-18 09:41
The zibo 738 need a patch to work, this isn't something I can fix. The patch has been submitted to Zibo, but I don't know if he's already integrated it.
Please clarify what "joystick setting about steering wheel" means.

**Comment by cpuwolf** [comment] 2017-07-18 10:14
OK thank you. maybe my understanding is wrong. will update to you later

**Comment by skiselkov** [comment] 2017-07-18 10:31
I'll close this issue for now. Just make sure you are running the latest Zibo mod version, he added support for BP in version 3.05e.
Should you run into some trouble, feel free to open another issue.

**Closed by skiselkov** 2017-07-18 10:31 UTC
Labels: invalid, question

**Comment by cpuwolf** [comment] 2017-07-31 03:58
latest version works fine
