### ISSUE TITLE
Crashing X-Plane

### ISSUE THREAD

**Issue by qwassss** [skiselkov/BetterPushbackC#6] opened 2017-07-15 18:18 UTC
First of all, thanks for all your hard work bringing a great tool like this to the community!

I'm having issues while testing it out. I can plan my push-back, but I don't get any auditory confirmation of the route being planned. Then, when I start the push back, X-Plane hard crashes.

I've attached the Log.txt file for your reference.
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1150520/Log.txt)

Thanks!

**Comment by skiselkov** [comment] 2017-07-15 20:32
Closing as duplicate of #2 This will be fixed shortly.

**Closed by skiselkov** 2017-07-15 20:32 UTC
Labels: bug, duplicate
