### ISSUE TITLE
Zibo last version 3.06h

### ISSUE THREAD

**Issue by alessandro61** [skiselkov/BetterPushbackC#110] opened 2017-08-18 09:14 UTC
Hello,

I have issue with your last pushback version and zibo 3.06h.
Here log.txt
Thanks and regards.
Alessandro
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1233895/Log.txt)

**Comment by skiselkov** [comment] 2017-08-18 09:16
Please describe the issue, because the Log file doesn't tell me.

**Comment by alessandro61** [comment] 2017-08-18 09:44
Ok.
Two screenshots. PB never stops with engines on. May be Zibo problem.

**Comment by skiselkov** [comment] 2017-08-18 10:00
You didn't attach any screenshots.

**Comment by skiselkov** [comment] 2017-08-18 10:08
Please record a video. I just tested with 3.06h and cannot reproduce any problem.

**Comment by beattleboy** [comment] 2017-08-18 10:21
I just tested with 3.06h and .43...   I got no issues as well.  Worked very nicely I might add.

**Comment by skiselkov** [comment] 2017-08-18 10:25
Ok, closing

**Closed by skiselkov** 2017-08-18 10:25 UTC
Labels: invalid, question

**Comment by alessandro61** [comment] 2017-08-18 12:04
Hi,

Problem and issue solved! Thanks and regards!!
Alessandro 

Inviato da iPhone

**Comment by skiselkov** [comment] 2017-08-18 12:05
@alessandro61 Can you please detail what you did to resolve the issue? Maybe I can automate the process in future releases.

**Comment by alessandro61** [comment] 2017-08-18 12:14
It is quite common to play new update without reading release notes. In my case, I have switched on taxi lignts during PB, ruining driver's eyesight. That's reason...I guess. Aircraft begins to move  around as crazy.
Btw, I appreciate very much your PB.
Alessandro

Inviato da iPhone
